### ISSUE TITLE
Filter on pass_length and pass_location

### ISSUE THREAD

**Issue by soricinae** [tuckerboynton22/nflfastr_app#1]
On the index page, add filters for: 
pass_length = short | deep
pass_location = left | middle | right

Use case: I would like to see which QBs are the best at throwing in the middle of the field

These are columns in the nflfastr pbp file

**Comment by tuckerboynton22** [comment]
Added pass location as a filter but assume it's easiest to filter by air yards to get the exact distance you're looking for
